server:
  port: ${MANAGE_SERVICE_PORT}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false
      file: manage-docker-compose.yml
  cache:
    cache-names:
      - security/acl
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://${CREDIT_PG_HOST}:${CREDIT_PG_PORT}/${CREDIT_PG_DATABASE}
    username: ${CREDIT_PG_USER}
    password: ${CREDIT_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

credit:
  payment-duration: 30d

app:
  token:
    secret: ${CLIENT_SECRET}
  session:
    duration: 24h