server:
  port: ${MANAGE_SERVICE_PORT}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties], keys/jwt-secrets.yml, keys/mail-keys.yml
  docker:
    compose:
      enabled: false
      file: manage-docker-compose.yml

  datasource:
    url: jdbc:postgresql://${CREDIT_PG_HOST}:${CREDIT_PG_PORT}/${CREDIT_PG_DATABASE}
    username: ${CREDIT_PG_USER}
    password: ${CREDIT_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}


credit:
  payment-duration: 30d

app:
  token:
    secret: ${secret.client}
  session:
    duration: 24h