server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: abs-auth-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false
      file: auth-database-local-docker-compose.yml
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
#    url: ${DOCKER_AUTH_POSTGRES_URL}
    url: jdbc:postgresql://localhost:${AUTH_PG_PORT}/${AUTH_PG_DATABASE}
    username: ${AUTH_PG_USER}
    password: ${AUTH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

security:
  token:
    client-secret: ${CLIENT_SECRET}
    microservice-secret: ${MICROSERVICE_SECRET}
  session:
    duration: 24h