server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false
      file: auth-database-local-docker-compose.yml
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

security:
  token:
    client-secret: ${CLIENT_SECRET}
    microservice-secret: ${MICROSERVICE_SECRET}
  session:
    duration: 24h