server:
  port: 8080

spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/${AUTH_PG_DATABASE}
    username: ${AUTH_PG_USER}
    password: ${AUTH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver