spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: ${DOCKER_AUTH_POSTGRES_URL}
    username: ${AUTH_PG_USER}
    password: ${AUTH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver