server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false
      file: auth-docker-compose.yml
#  cache:
#    cache-names:
#      - security/acl
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  acl-datasource:
    url: jdbc:postgresql://${AUTH_PG_HOST}:${AUTH_PG_PORT}/${AUTH_PG_DATABASE}
    username: ${AUTH_PG_USER}
    password: ${AUTH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  token:
    secret: d23bea1775b4d94df57db8afd49a5a7461703d94ebd54173a8b92aeeaaca4a88
  session:
    duration: 24h