create table users (
    id int primary key generated by default as identity,
    email varchar(100) unique,
    password varchar(512),
    name varchar(50),
    employment varchar(100)
);

create table roles (
    id int primary key generated by default as identity,
    name varchar(15)
);
insert into roles (name) values ('ROLE_ADMIN'),
                                ('ROLE_OPERATOR'),
                                ('ROLE_CLIENT');

create table user_role (
    user_id int references users(id),
    role_id int references roles(id),
    primary key (user_id, role_id)
);

create table sessions (
    id bigint primary key generated by default as identity,
    user_id int references users(id),
    issued_at timestamp,
    expired_at timestamp,
    is_enable boolean
);

create table acl_sid(
    id bigint primary key generated by default as identity,
    principal boolean,
    sid varchar(100),
    constraint unique_uk_1 unique(sid, principal)
);

create table acl_class(
    id bigint primary key generated by default as identity,
    class varchar(500) unique,
    class_id_type varchar(500)
);

create table acl_object_identity(
    id bigint primary key generated by default as identity,
    object_id_class bigint references acl_class(id),
    object_id_identity varchar(36),
    parent_object bigint references acl_object_identity(id),
    owner_sid bigint references acl_sid(id),
    entries_inheriting boolean,
    constraint unique_uk_3 unique(object_id_class, object_id_identity)
);

create table acl_entry(
    id bigserial primary key,
    acl_object_identity bigint,
    ace_order int,
    sid bigint,
    mask integer,
    granting boolean,
    audit_success boolean,
    audit_failure boolean,
    constraint unique_uk_4 unique(acl_object_identity,ace_order),
    constraint foreign_fk_4 foreign key(acl_object_identity) references acl_object_identity(id),
    constraint foreign_fk_5 foreign key(sid) references acl_sid(id)
);

create table employees (
    id int references users(id) primary key,
    position varchar(50),
    manager_id int,
    foreign key (manager_id) references employees(id)
);

insert into users(email, password, name, employment)
values ('email1@gmail.com', 'password1', 'name1', 'employment1');

insert into user_role(user_id, role_id) values (1, 1),
                                               (1, 3);
