services:
  auth-service:
    build:
      dockerfile: auth-service.dockerfile
    container_name: "auth-service"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    networks:
      - abs_service_network

networks:
  abs_service_network:
    external: true