services:
  postgres:
    container_name: "auth-postgres"
    env_file:
      - .env
    image: 'postgres:16.4'
    environment:
      POSTGRES_USER: ${AUTH_PG_USER}
      POSTGRES_PASSWORD: ${AUTH_PG_PASSWORD}
      POSTGRES_DB: ${AUTH_PG_DATABASE}
    ports:
      - "${AUTH_PG_PORT}:5432"
    networks:
      - abs_service_network

  flyway:
    container_name: "auth-flyway"
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${AUTH_PG_DATABASE}
      FLYWAY_USER: ${AUTH_PG_USER}
      FLYWAY_PASSWORD: ${AUTH_PG_PASSWORD}
    command:
      - migrate
    volumes:
      - ./auth-service/src/main/resources/flyway/migrations:/flyway/sql
    image: 'flyway/flyway:11.4'
    depends_on:
      postgres:
        condition: service_started
        restart: true
    networks:
      - abs_service_network

networks:
  abs_service_network:
    external: true