services:
  credit_db_postgres:
    container_name: "credit-postgres"
    env_file:
      - .env
    image: 'postgres:16.4'
    environment:
      POSTGRES_USER: ${CREDIT_PG_USER}
      POSTGRES_PASSWORD: ${CREDIT_PG_PASSWORD}
      POSTGRES_DB: ${CREDIT_PG_DATABASE}
    ports:
      - "${CREDIT_PG_PORT}:5432"
    networks:
      - abs_service_network

  credit_flyway:
    container_name: "credit-flyway"
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://credit_db_postgres:5432/${CREDIT_PG_DATABASE}
      FLYWAY_USER: ${CREDIT_PG_USER}
      FLYWAY_PASSWORD: ${CREDIT_PG_PASSWORD}
    command:
      - migrate
    volumes:
      - ./manage-service/src/main/resources/flyway/migrations:/flyway/sql
    image: 'flyway/flyway:11.4'
    depends_on:
      credit_db_postgres:
        condition: service_started
        restart: true
    networks:
      - abs_service_network

  abs-service:
    build:
      dockerfile: Dockerfile
    container_name: "abs-service"
    env_file:
      - .env
    environment:
      CREDIT_PG_HOST: credit_db_postgres
      CREDIT_PG_PORT: 5432
    ports:
      - "${MANAGE_SERVICE_PORT}:8080"
    depends_on:
      - credit_db_postgres
    networks:
      - abs_service_network

networks:
  abs_service_network:
    name: "abs-network"
    driver: bridge