services:
  nginx:
    container_name: ${NGINX_SERVER_PROJECT_NAME}
    env_file:
      - .env
    image: nginx:1.27.4
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${NGINX_PORT}:80"