server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: true
      file: auth-docker-compose.yml
#  cache:
#    cache-names:
#      - security/acl
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://${AUTH_PG_HOST}:${AUTH_PG_PORT}/${AUTH_PG_DATABASE}
    username: ${AUTH_PG_USER}
    password: ${AUTH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

#  acl-datasource:
#    url: jdbc:postgresql://${AUTH_PG_HOST}:${AUTH_PG_PORT}/${AUTH_PG_DATABASE}
#    username: ${AUTH_PG_USER}
#    password: ${AUTH_PG_PASSWORD}
#    driver-class-name: org.postgresql.Driver

security:
  token:
    client-secret: ${CLIENT_SECRET}
    microservice-secret: ${MICROSERVICE_SECRET}
  session:
    duration: 24h