server:
  port: ${INFO_SERVICE_POST}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  cache:
    cache-names:
      - security/acl
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#  datasource:
#    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
#    username: ${PG_USER}
#    password: ${PG_PASSWORD}
#    driver-class-name: org.postgresql.Driver

  acl-datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

credit:
  payment-duration: 30d

app:
  token:
    secret: FKHkJNhkjd2dhsNiOghNi4513qjkHtyufTd3wydsjg7SAfUYFdv
  session:
    duration: 24h