server:
  port: ${GATEWAY_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_POST}
          predicates:
            - name: authentication

        - id: information-service
          uri: ${INFO_SERVICE_POST}
          predicates:
            - name: information
