http:
  routers:
    myapp:
      rule: "PathPrefix(`/auth`)"
      service: myapp-service
  services:
    myapp-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8071"