http:
  routers:
    myapp:
      rule: "PathPrefix(`/auth`)"
      service: auth-service
      middlewares:
        - strip-auth

  middlewares:
    strip-auth:
      stripPrefix:
        prefixes:
          - "/auth"

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8080"