services:
  traefik:
    image: traefik:v3.3
    container_name: "traefik"
    env_file:
      - ../.env
    ports:
      - "${TRAEFIK_PORT}:80"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - abs_service_network

networks:
  abs_service_network:
    external: true