server:
  port: ${INFO_SERVICE_PORT}

spring:
  application:
    name: abs-info-service
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DOCKER_AUTH_POSTGRES_URL}
    username: ${AUTH_PG_USER}
    password: ${AUTH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

security:
  token:
    microservice-secret: ${MICROSERVICE_SECRET}