server:
  port: ${INFO_SERVICE_PORT}

spring:
  application:
    name: abs-info-service
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${CREDIT_PG_DATABASE}
    username: ${CREDIT_PG_USER}
    password: ${CREDIT_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  graphql:
    graphiql:
      enabled: true

security:
  token:
    microservice-secret: ${MICROSERVICE_SECRET}