create table credit_tariffs (
    id int primary key generated by default as identity,
    type varchar(100),
    up_to_amount numeric(15, 2),
    up_to_credit_period int,
    credit_percent int
);
insert into credit_tariffs (type, up_to_amount, up_to_credit_period, credit_percent)
values ('t1', 1000000, 24, 16),
       ('t2', 2000000, 36, 16),
       ('t3', 3000000, 48, 15),
       ('t4', 4000000, 60, 15),
       ('t5', 5000000, 72, 14);

create table credit_requests (
    id bigint primary key generated by default as identity,
    credit_tariff_id int references credit_tariffs(id),
    credit_amount numeric(15, 2),
    credit_duration int,
    created_at timestamp,
    user_id int
);

create table credits_scoring (
    score numeric(15, 2),
    credit_request_id bigint primary key references credit_requests(id),
    status varchar(10)
);

create table credits (
    id bigint primary key generated by default as identity,
    initial_amount numeric(15, 2),
    taking_date date,
    percent int,
    credit_period int,
    month_amount numeric(15, 2),
    credit_status varchar(10),
    user_id int,
    credit_tariff_id int references credit_tariffs(id)
);

create table balances (
    id bigint primary key generated by default as identity,
    credit_id int references credits(id),
    remaining_debt numeric(15, 2),
    remaining_month_debt numeric(15, 2),
    accrued_by_percent numeric(15, 2),
    created_at date
);

create table penalties (
    id bigint primary key generated by default as identity,
    credit_id bigint references credits(id),
    type varchar(20),
    amount numeric(15, 2),
    status varchar(10),
    created_at date
);

create table payments (
    id bigint primary key generated by default as identity,
    credit_id bigint references credits(id),
    amount numeric(15, 2),
    commission_amount decimal(15, 2),
    created_at timestamp
);

truncate table credits cascade;
alter sequence credits_id_seq restart with 1;
